### ISSUE TITLE
Difference between versions?

### ISSUE THREAD

**Issue by mhulse** [ten-A/AiMenuObject#3]
Hello! Thanks for this code.

What is difference between v22 and v23?

- **v22:** https://github.com/ten-A/AiMenuObject/blob/99b5ba4fbdacee86b7a5f63b8eeb9f0a6351cc2b/AiMenu_v22.jsxinc
- **v23:** https://github.com/ten-A/AiMenuObject/blob/99b5ba4fbdacee86b7a5f63b8eeb9f0a6351cc2b/AiMenu_v23.jsxinc

Also, have you considered using GitHub's releases?

https://github.com/ten-A/AiMenuObject/releases

Could be cool to have v22 and v23 be organized as releases?

Thanks so much!!!! 👍

**Comment by ten-A** [comment]
I have taken care of some issue and these are almost the same menu structure, excepts "Show Gradient Guide" menu command.

**Comment by ten-A** [comment]
These libraries still testing purpose and I have no plan to release, yet.

**Comment by mhulse** [comment]
Ah, great, thanks for the clarification and help! I really appreciate it!!!

Thanks for the code too! :)

Have a nice day!
